### ISSUE TITLE
Embed a probe into the image

### ISSUE THREAD

**Issue by erthalion** [stackrox/collector#1019]
Modify the build pipeline to embed a probe into the image. Here we don't have to bother yet what probe is that, for testing as close as possible to the reality we could e.g. build a vanilla falco modern probe with libsinsp example and use it. This will involve similar steps, e.g. actual building of something, fetching a new dependency (libbpf) etc.

Part of #1014

**Comment by ovalenti** [comment]
@erthalion, with the use of embedded skeleton, does this task still apply ?

**Comment by erthalion** [comment]
Not for MVP, but it's still necessary for the following release (see the parent issue #1014).
