### ISSUE TITLE
Extend existing sinsp-example based tests

### ISSUE THREAD

**Issue by erthalion** [stackrox/collector#1043]
Falco library features two sets of tests for probes:

* [e2e tests][e2e] based on `sinsp-example`. They allow to simulate a variety of low-level events relatively easy, don't support modern probes directly.
* [drivers test suite][drivers]. More basic unit-tests following the strategy "fire a syscall and verify what the driver has captured", supports modern probes as well.

Figure out of those two cover the functionality of modern probes good enough, and if not, extend to improve that and include into the testing pipeline.

Part of #1008 

[e2e]: https://github.com/falcosecurity/libs/tree/master/test/e2e
[drivers]: https://github.com/falcosecurity/libs/tree/master/test/drivers

**Comment by Molter73** [comment]
I'll start working on adding the modern probe to the e2e tests now, it's been in my todo list for far too long.

The drivers test suite was born as a way to test the modern probe, so AFAIK, it should have 100% coverage (or close to it) for the features implemented in it. I'll take a look and make sure it does though.

**Comment by Molter73** [comment]
I've created a PR upstream to run the e2e tests with the modern probe: https://github.com/falcosecurity/libs/pull/967
