### ISSUE TITLE
btf/vmlinux for Collector

### ISSUE THREAD

**Issue by erthalion** [stackrox/collector#1045]
Modern probe require `/sys/kernel/btf/vmlinux` present and available from the Collector container. Currently it is actually the case at least for OCP 4.12 -- a privileged container is able too read `vmlinux` file without any extra mounts. At the same time Collector is mounting host `sysfs` under `/host/` path, including required `vmlinux` file. What needs to be done:

* Figure out, if we can rely on `vmlinux` present by K8S/OCP in a privileged container? Is it completely the same as what is mounted from the host via `/host` path?
* If those are not the same, or `vmlinux` file is not provided on all supported platforms, make sure it's included into the current `sysfs` mounts into the Collector container. If not, add it into the DaemonSet definition.
* If `vmlinux` will end up by the path different from `/sys/kernel/btf/vmlinux` or one of other standard locations (`/boot/vmlinux...`, `/lib/modules/...`, `/usr/lib/modules/...`, see `libbpf` for more details), Falco modern bpf engine has to be extended to pass load options for the probe. This would be probably a separate task from this one.

Part of #1015

**Comment by Stringy** [comment]
I have been able to confirm that `/host/sys/kernel/btf/vmlinux` matches `/sys/kernel/btf/vmlinux` on Openshift 4:

```
sh-4.4# sha256sum /host/sys/kernel/btf/vmlinux
b45e80b38f6d153f4e896fa12fc97afb1fde5952e16866f9b6ad2c0421577924  /host/sys/kernel/btf/vmlinux
sh-4.4# sha256sum /sys/kernel/btf/vmlinux
b45e80b38f6d153f4e896fa12fc97afb1fde5952e16866f9b6ad2c0421577924  /sys/kernel/btf/vmlinux
sh-4.4#
```

and this also matches the vmlinux on the node itself:
```
[root@gdth-03-17-childlike-nxbl8-worker-b-2gfp7 ~]# sha256sum /sys/kernel/btf/*
b45e80b38f6d153f4e896fa12fc97afb1fde5952e16866f9b6ad2c0421577924  /sys/kernel/btf/vmlinux
```

I will now verify on GKE or similar.

**Comment by Stringy** [comment]
Verified on GKE:

Collector pod
```
[root@collector-8xsm7 /]# sha256sum /sys/kernel/btf/vmlinux
2cff4f49a292a51e3d86683fb82219932c7eeaedeebeba5f2b1e2a9d16a994d6  /sys/kernel/btf/vmlinux
[root@collector-8xsm7 /]# sha256sum /host/sys/kernel/btf/vmlinux
2cff4f49a292a51e3d86683fb82219932c7eeaedeebeba5f2b1e2a9d16a994d6  /host/sys/kernel/btf/vmlinux
[root@collector-8xsm7 /]#
```

Node:
```
root@gke-gdth-03-17-annoying--default-pool-8970f747-2r97:/home/ghutton# sha256sum /sys/kernel/btf/vmlinux
2cff4f49a292a51e3d86683fb82219932c7eeaedeebeba5f2b1e2a9d16a994d6  /sys/kernel/btf/vmlinux
root@gke-gdth-03-17-annoying--default-pool-8970f747-2r97:/home/ghutton#
```
