### ISSUE TITLE
Kernel Version is not supported

### ISSUE THREAD

**Issue by nenov92** [stackrox/collector#1518]
The latest gardenlinux-cloud kernel version - 6.1.63-gardenlinux-cloud-amd64 is not supported. The most recent supported version is 5.15.114-gardenlinux-cloud-amd64 (already quite old). We won't be able to use stackrox if this isn't fixed soon.

**Comment by Stringy** [comment]
Hi @nenov92, we are in the process of phasing out and eventually deprecating/removing eBPF support in Collector, which I believe is why newer Garden Linux kernels are unsupported.

However, if you switch your collection method to core-bpf, then your collectors should work again. core-bpf is our new collection method that will work on the vast majority of kernels out-of-the-box.

**Comment by nenov92** [comment]
Hi @Stringy. We updated the collection method to core-bpf and now StackRox works successfully with the newer Linux kernels. Thank you for your help!
