### ISSUE TITLE
Problem to download specific kernel module 

### ISSUE THREAD

**Issue by jenciso** [stackrox/collector#818]
Hi.
My AKS uses the kernel 5.4.0-1089-azure, so it needed the kernel module collector-5.4.0-1089-azure.ko.gz. But I haven't been  seeing it here:

https://collector-modules.stackrox.io/612dd2ee06b660e728292de9393e18c81a88f347ec52a39207c5166b5302b656/b6745d795b8497aaf387843dc8aa07463c944d3ad67288389b754daaebea4b62/collector-5.4.0-1089-azure.ko.gz

However, other modules are there, e.g.  [collector-5.4.0-1086-azure.ko.gz](https://collector-modules.stackrox.io/612dd2ee06b660e728292de9393e18c81a88f347ec52a39207c5166b5302b656/b6745d795b8497aaf387843dc8aa07463c944d3ad67288389b754daaebea4b62/collector-5.4.0-1086-azure.ko.gz)

I think that collector-modules.starox.io is the right domain to look up new modules. My stackrox version is 3.0.62.0

I want to notify this behavior and request to upload the module mentioned. I appreciate any help you can provide.

**Comment by erthalion** [comment]
Hi,

We will take a look at what happened with this particular module, but stackrox
3.0.62.0 seems to be quite old. There are modules for this kernel flavour
available for probes v2.1.0, so simply updating should solve the issue.

**Comment by jenciso** [comment]
Yes @erthalion. We upgraded the stackrox version and now it works! Thanks for your reply

**Comment by erthalion** [comment]
Great, thank you!
