### ISSUE TITLE
collector logging running amok

### ISSUE THREAD

**Issue by Elyytscha** [stackrox/collector#935]
![image](https://user-images.githubusercontent.com/10408311/206753700-34135d21-4bc0-4e31-9227-9653b950c3f5.png)

our aggregated logging was exploding due to stackrox collector logging.. there where millions of lines like this the last days from 3/10 collector nodes..

actually to mitigate as fast as possible we had to delete stackrox

this is the error message which where present millions of times, this message appaered on 3 from 10 collector nodes about 6-10 times every millisecond..
`[E 20221209 165715 ConnScraper.cpp:415] Could not determine network namespace: No such file or directory`

it was deployed like this:
`/bin/bash <(curl -fsSL https://raw.githubusercontent.com/stackrox/stackrox/master/scripts/quick-helm-install.sh)`

on gke v1.24

**Comment by ovalenti** [comment]
@Elyytscha, thanks for this confirmation of the release channel. We will make sure to fix the logging flood soon.

Would you be aware of a common factor to these 3 nodes having the issue ? Is something different about them relatively to the other 7 ones ?

We will try to reproduce the issue, but in the meantime, it would greatly help if you could provide us with the result of `ls -lR /proc/xxxx` on the host of a failing node, replacing xxxx by any PID available.

**Comment by ovalenti** [comment]
@Elyytscha, based on the early analysis of this issue, it seems that you should be able to workaround by disabling the `scraper` component of collector. This can be achieved by modifying the daemonset definition and set `"turnOffScrape"` to _true_ in the `COLLECTOR_CONFIG` env var.

https://github.com/stackrox/collector/blob/master/docs/references.md#collector-config

**Comment by Elyytscha** [comment]
Hello,

first I wanted to say thanks for your help! This is not self-evident within opensource projects, to get answers that fast.




> Would you be aware of a common factor to these 3 nodes having the issue ? Is something different about them relatively to the other 7 ones ?
> 

no, those nodes a from the same resource pool, the only difference to other nodes could be the pods which get scheduled to those nodes

maybe some information is that we use calico as SDN

this info i can give about pods running on one of the affected nodes (but its possible that the pods which caused this could be  already scheduled to another node..)
![stackrox_debug](https://user-images.githubusercontent.com/10408311/207306898-be80017b-531b-4811-a321-283b0d9afc0d.png)


> We will try to reproduce the issue, but in the meantime, it would greatly help if you could provide us with the result of `ls -lR /proc/xxxx` on the host of a failing node, replacing xxxx by any PID available.

be prepared, the logfile i got for this is long.. its so big, i had to split it into two files, but i think what you want to see you will find there, because there are also 'No such file or directory' messages
[getpids.log](https://github.com/stackrox/collector/files/10217815/getpids.log)
[getpids.2.log](https://github.com/stackrox/collector/files/10217820/getpids.2.log)


> @Elyytscha, based on the early analysis of this issue, it seems that you should be able to workaround by disabling the `scraper` component of collector. This can be achieved by modifying the daemonset definition and set `"turnOffScrape"` to _true_ in the `COLLECTOR_CONFIG` env var.

There i have some questions:
1. Which functionality from stackrox will be disabled/unavailable if we turn this off?
2. Is this possible via the helm chart? https://github.com/stackrox/helm-charts/blob/5cd826a14d7c30d1b7ca538b4ff71d1723339a2c/3.72.2/secured-cluster-services/values-public.yaml.example#L324 would this be the right place for setting this env var?

**Comment by Elyytscha** [comment]
We fixed it, the issue was due to our old docker in docker container build system, for new systems we actually use kaniko but for old legacy systems there are docker builds via dockerd in a containerd system, we fixed it basically due to this comment:
https://github.com/docker-library/docker/issues/318#issuecomment-882835825 

docker has added tini as docker-init in their container and we used it with:
```
ENTRYPOINT ["docker-init", "--", "dockerd-entrypoint.sh"]
```

after this we had no zombie/defunct processes anymore after docker in docker build where running.

**but still** i think it would be a good idea to limit those log messages stackrox btw. collector will produce in such a situation.

the situation appears when there are zombie/defunct processes from old containers which somehow dont get reaped.

**Comment by JoukoVirtanen** [comment]
Glad to hear that you resolved your problem. Thanks for bringing this to our attention. Based on this experience we plan a few improvements to collector including throttling of logging statements and better handling of defunct processes.
